module.exports = {
  API:'https://hacker-news.firebaseio.com/v0/',
  RECEIVE_NEWS: 'RECEIVE_NEWS',
  RECEIVE_USER: 'RECEIVE_USER',
  RECEIVE_NEWEST: 'RECEIVE_NEWEST',
  NO_MORE_NEWS: 'NO_MORE_NEWS',
  NO_MORE_NEWEST: 'NO_MORE_NEWEST',
  NO_MORE_SHOW: 'NO_MORE_SHOW',
  RECEIVE_SHOW: 'RECEIVE_SHOW',
  NO_MORE_ASK: 'NO_MORE_ASK',
  RECEIVE_ASK: 'RECEIVE_ASK',
  RECEIVE_COMMENT: 'RECEIVE_COMMENT'

}
